name: Build and Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

env:
  packageName: "2048"
  packagePath: "dist"
  packageFileName: "2048"
  packageReleaseName: "2048"

permissions:
  contents: write

jobs:
  build_and_release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
    
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install pyinstaller
        run: pip install pyinstaller

      - name: Build executable
        run: pyinstaller --onefile --name 2048 2048.py

      - name: List files in dist directory
        run: ls -la dist

      - name: Upload executable as artifact
        uses: actions/upload-artifact@v2
        with:
          name: 2048-executable
          path: dist/2048.exe

      - name: Download executable artifact
        uses: actions/download-artifact@v2
        with:
          name: 2048-executable
          path: ./dist

      - name: Get Current Version
        id: get_version
        run: echo "version=$(cat VERSION)" >> $GITHUB_ENV

      - name: Increment Version
        id: increment_version
        run: |
          version=${{ env.version }}
          echo "Current version: $version"
          IFS='.' read -r -a parts <<< "$version"
          major=${parts[0]}
          minor=${parts[1]}
          patch=${parts[2]}
          new_patch=$((patch + 1))
          new_version="$major.$minor.$new_patch"
          echo "New version: $new_version"
          echo $new_version > VERSION
          echo "new_version=$new_version" >> $GITHUB_ENV

      - name: Commit New Version
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add VERSION
          git commit -m "Increment version to ${{ env.new_version }}"
          git tag "v${{ env.new_version }}"
          git push origin --tags
          git push

      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@de2c0eb89ae2a093876385947365aca7b0e5f844
        with:
          name: "${{ env.packageReleaseName }} v${{ env.new_version }}"
          tag_name: "v${{ env.new_version }}"
          files: |
            ./dist/2048.exe
